
name: sta_ursula_booking_app
description: A simple church reservation app.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/church.jpg
    - assets/front.jpg
    - assets/wedding.avif
    - assets/funeral.jpeg 
    - assets/christening.jpg
    - assets/profile.avif

